const data = [
    {
    "name": "Saccharose",
    "symbol": "Sa",
    "othernames": "Haushaltszucker",
    "enumber": "",
    "containedin": "",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 1,
    "calories": 387,
    "gi": 65,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Wird mit Nierenerkrankungen, Gicht und Fettlebererkrankungen in Verbindung gebracht"
  },
  {
    "name": "Brauner Zucker",
    "symbol": "Br",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 1,
    "calories": 380,
    "gi": 64,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Spurenmengen an Nährstoffen; hauptsächlich Saccharose"
  },
  {
    "name": "Honig",
    "symbol": "Hn",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (roh)",
    "cat-nr": 1,
    "sweetness": 0.97,
    "calories": 309,
    "gi": 60,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "Enthält Antioxidantien, kann aber Pestizide enthalten; gefährlich für Kleinkinder"
  },
  {
    "name": "Yacón-Sirup",
    "symbol": "Yc",
    "othernames": "Yacón-Pulver",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (roh)",
    "cat-nr": 1,
    "sweetness": 0.5,
    "calories": 219,
    "gi": 5,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Reich an Ballaststoffen; Die tägliche Einnahme kann zu Gewichtsverlust führen"
  },
  {
    "name": "Mönchsfrucht",
    "symbol": "Mf",
    "othernames": "Lu Han Guo",
    "enumber": "",
    "containedin": "(exotische) Getränke",
    "category": "Naturstoff (roh)",
    "cat-nr": 1,
    "sweetness": 300,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Alter chinesischer Süßstoff; manchmal mit Dextrose „schneiden“."
  },
  {
    "name": "Lucuma-Pulver",
    "symbol": "Lu",
    "othernames": "",
    "enumber": "",
    "containedin": "Nahrungsergänzungsmittel",
    "category": "Naturstoff (roh)",
    "cat-nr": 1,
    "sweetness": 0.5,
    "calories": 329,
    "gi": 25,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Laut Verbraucherzentrale liegen kaum wissenschaftliche Studien zu möglichen (Langzeit-) Risiken, Wechselwirkungen mit Medikamenten, zum allergenen Potential oder auch zur Bioverfügbarkeit vor."
  },
  {
    "name": "Zuckerrohrmelasse",
    "symbol": "Zm",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": 0.8,
    "calories": 290,
    "gi": 55,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Hauptsächlich Saccharose; enthält Antioxidantien, Mineralien und B-Vitamine"
  },
  {
    "name": "Thaumatin",
    "symbol": "Th",
    "othernames": "",
    "enumber": "E 957",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": "",
    "calories": "",
    "gi": "",
    "tooth": "",
    "heat": "nein",
    "laxative": "",
    "aftertaste": "",
    "fructose-intolerance": "",
    "notes": "Besteht aus Proteinen, die aus der westafrikanischen Katamfrucht isoliert werden."
  },
  {
    "name": "Kokosblütenzucker",
    "symbol": "Kb",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": "",
    "calories": "",
    "gi": "",
    "tooth": "",
    "heat": "",
    "laxative": "",
    "aftertaste": "",
    "fructose-intolerance": "",
    "notes": ""
  },
  {
    "name": "Agavendicksaft",
    "symbol": "Ag",
    "othernames": "Agavensirup",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": 1.3,
    "calories": 310,
    "gi": 15,
    "tooth": "ja",
    "heat": "",
    "laxative": "",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "enthält sehr viel Fruktose"
  },
  {
    "name": "Ahornsirup",
    "symbol": "As",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": 1,
    "calories": 260,
    "gi": 65,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "Hauptsächlich Saccharose; enthält Antioxidantien, Mineralien und B-Vitamine"
  },
  {
    "name": "Sorghumsirup",
    "symbol": "Sg",
    "othernames": "Zuckerhirse",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": 1.1,
    "calories": 290,
    "gi": 50,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Hauptsächlich Saccharose; enthält Antioxidantien, Mineralien und B-Vitamine"
  },
  {
    "name": "Glycyrrhizin",
    "symbol": "Gl",
    "othernames": "Süßholz, Lakritze",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": 50,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose-intolerance": "",
    "notes": "kann im Übermaß Bluthochdruck auslösen"
  },
  {
    "name": "Steviaglycoside",
    "symbol": "St",
    "othernames": "Stevia",
    "enumber": "E960",
    "containedin": "Getränke, Süßigkeiten, Fruchtaufstriche",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 2,
    "sweetness": 300,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "bedingt (bis 150 Grad)",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose-intolerance": "ja",
    "notes": "Laut der Europäischen Behörde für Lebensmittelsicherheit (EFSA) sollte man täglich nicht mehr als 4 Milligramm Steviaglycoside pro Kilogramm Körpergewicht aufnehmen. Kinder können den Wert schnell überschreiten, vor allem beim Verzehr von steviagesüßten Getränken."
  },
  {
    "name": "Isoglukose",
    "symbol": "Ig",
    "othernames": "Maissirup, High-Fructose-Corn-Syrup (HFCS), Fruktose-Glukose-Sirup",
    "enumber": "",
    "containedin": "Limonaden, Desserts, Süßigkeiten",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 1.2,
    "calories": 281,
    "gi": 60,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "Besteht, wie Haushaltszucker, aus Fructose und Glucose. Der Anteil an Fructose kann bis zu 90 Prozent betragen."
  },
  {
    "name": "Invertzucker",
    "symbol": "In",
    "othernames": "Invertose, Invertzuckersirup",
    "enumber": "",
    "containedin": "Cocktails, Süßigkeiten, Müsliriegel",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 1.2,
    "calories": 387,
    "gi": 60,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "Ernährungsphysiologisch wie Saccharose. Wird wegen seiner flüssigen Konsistenz gerne zur Süßung von Cocktails und Bonbonfüllungen verwendet."
  },  
  {
    "name": "Galaktose",
    "symbol": "Ga",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 0.6,
    "calories": 400,
    "gi": 20,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Schädlich für Menschen, die es nicht verdauen können"
  },
  {
    "name": "Glukose",
    "symbol": "Gl",
    "othernames": "Traubenzucker",
    "enumber": "",
    "containedin": "",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 0.7,
    "calories": 400,
    "gi": 100,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Reduziert den Appetit; lässt den Blutzuckerspiegel schnell ansteigen"
  },
  {
    "name": "Tagatose",
    "symbol": "Tg",
    "othernames": "",
    "enumber": "",
    "containedin": "PepsiCo (USA)",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 0.9,
    "calories": 150,
    "gi": 3,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Senkt den Blutzuckerspiegel bei Menschen mit erhöhtem Blutzucker"
  },
  {
    "name": "Maltose",
    "symbol": "Ma",
    "othernames": "Malzzucker",
    "enumber": "",
    "containedin": "Brauner Reissirup",
    "category": "Zucker",
    "cat-nr": 3,
    "sweetness": 0.5,
    "calories": 400,
    "gi": 105,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Der Arsengehalt im Sirup ist oft höher als empfohlen"
  },
  {
    "name": "Polyglycitolsirup",
    "symbol": "Pg",
    "othernames": "hydrierter Glucosesirup",
    "enumber": "E 964",
    "containedin": "Speiseeis",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.8,
    "calories": 240,
    "gi": "",
    "tooth": "",
    "heat": "",
    "laxative": "ja",
    "aftertaste": "",
    "fructose-intolerance": "nein",
    "notes": "Wegen seiner flüssigen Konsistenz gut geeignet für Speiseeis und andere Süßspeisen"
  },
  {
    "name": "Maltit",
    "symbol": "Ml",
    "othernames": "Süße Perle",
    "enumber": "E 965",
    "containedin": "",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.8,
    "calories": 210,
    "gi": 35,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "hat leichten Karamellgeschmack"
  },
  {
    "name": "Lactit",
    "symbol": "Lt",
    "othernames": "NH4-Redox",
    "enumber": "E 966",
    "containedin": "",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.4,
    "calories": 200,
    "gi": 3,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Wird aus Molke gewonnen"
  },
  {
    "name": "Xylit",
    "symbol": "Xy",
    "othernames": "Birkenzucker",
    "enumber": "E 967",
    "containedin": "Zahnpflege-Kaugummis",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 1,
    "calories": 240,
    "gi": 13,
    "tooth": "nein",
    "heat": "ja (\"koch- und backfest\")",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "bedingt",
    "notes": "Gut für die Zähne; Studien zufolge sollen große Mengen Xylit das Risiko für schwere Herzerkrankungen und Schlaganfälle deutlich erhöhen"
  },
  {
    "name": "Sorbit",
    "symbol": "Sb",
    "othernames": "",
    "enumber": "E 420",
    "containedin": "",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.6,
    "calories": 260,
    "gi": 9,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "Verlängert die Haltbarkeit von Lebensmitteln; manche Menschen sind allergisch; nicht für Reizdarm, kann abführend wirken"
  },
  {
    "name": "Mannit",
    "symbol": "Mn",
    "othernames": "",
    "enumber": "E 421",
    "containedin": "Süßwaren, Desserts, Kaugummis",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.7,
    "calories": 150,
    "gi": 2,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "Hartbeschichtung für Pillen; wird als Abführmittel genutzt"
  },
  {
    "name": "Isomalt",
    "symbol": "Is",
    "othernames": "",
    "enumber": "E 953",
    "containedin": "Bonbons, Kaugummis, Desserts",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.6,
    "calories": 200,
    "gi": 2,
    "tooth": "nein",
    "heat": "ja(?) bis ca. 150 Grad",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose-intolerance": "nein",
    "notes": "nimmt so gut wie keine Feuchtigkeit aus der Luft auf, verklumpt daher nicht"
  },
  {
    "name": "Erythrit",
    "symbol": "Er",
    "othernames": "",
    "enumber": "E 968",
    "containedin": "Kaugummis, Bonbons",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.7,
    "calories": 0,
    "gi": 1,
    "tooth": "nein",
    "heat": "nein",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "bedingt",
    "notes": "im Vergleich zu den anderen Zuckeralkoholen besonders verträglich"
  },
  {
    "name": "Saccharin",
    "symbol": "Sc",
    "othernames": "",
    "enumber": "E 954",
    "containedin": "Limonaden, Süßstofftabletten, Diätprodukten",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 550,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "bedingt (bis 150 Grad)",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose-intolerance": "ja",
    "notes": "Ältester Süßstoff auf dem deutschen Markt. Einst wegen der Entstehung von Blasenkrebs bei Ratten verboten"
  },
  {
    "name": "Sucralose",
    "symbol": "Sr",
    "othernames": "Splenda",
    "enumber": "E 955",
    "containedin": "",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 600,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "bedingt",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "ja",
    "notes": "Behält die kristalline Form auch bei großer Hitze; bleibt in der Umwelt bestehen"
  },
  {
    "name": "Aspartam",
    "symbol": "As",
    "othernames": "Canderel, Equal, NutraSweet",
    "enumber": "E 951",
    "containedin": "Getränke, Süßwaren, Desserts",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 200,
    "calories": 4,
    "gi": 0,
    "tooth": "nein",
    "heat": "bedingt (bis 195 Grad)",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "ja",
    "notes": "Erzeugt Formaldehyd im Körper; kann die Taille vergrößern"
  },
  {
    "name": "Acesulfam-Aspartam",
    "symbol": "Aa",
    "othernames": "",
    "enumber": "E 962",
    "containedin": "Getränke, Süßwaren, Desserts",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 350,
    "calories": "",
    "gi": 0,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "",
    "fructose-intolerance": "ja",
    "notes": ""
  },
  {
    "name": "Advantam",
    "symbol": "Ad",
    "othernames": "",
    "enumber": "E 969",
    "containedin": "Süßwaren, Brotaufstrich, Soßen",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 20000,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "bedingt",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "Abgeleitet von Aspartam; geschmacksverstärkend (insbesondere Citrus-, Frucht- und Minzaromen), Auswirkungen auf das Gehirn wurden nicht gründlich getestet"
  },
  {
    "name": "Neotam",
    "symbol": "Ne",
    "othernames": "",
    "enumber": "E 961",
    "containedin": "Backwaren, Senf",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 8000,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "",
    "notes": "„Fehlerhafte Sicherheitsstudien“, sagt das Center for Science in the Public Interest"
  },
  {
    "name": "Acesulfam-Kalium",
    "symbol": "Ac",
    "othernames": "Sunett",
    "enumber": "E 950",
    "containedin": "Getränke, Süßwaren, Zahnpasta",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 200,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "nein",
    "fructose-intolerance": "ja",
    "notes": "CSPI: „Sicherheitstests ... waren von mittelmäßiger Qualität.“"
  },
  {
    "name": "Cyclamat",
    "symbol": "Cy",
    "othernames": "",
    "enumber": "E 952",
    "containedin": "Limonaden, Süßstofftabletten, Diätprodukten",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 35,
    "calories": 0,
    "gi": 0,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "",
    "aftertaste": "nein",
    "fructose-intolerance": "ja",
    "notes": "Wird oft gemeinsam mit Saccharin eingesetzt, da die beiden ihre Süßkraft gegenseitig verstärken. Die erlaubte Tagesdosis beträgt 7 Milligramm pro Kilogramm Körpergewicht."
  }
]