const data = [
  {
    "name": "Saccharose",
    "symbol": "Su",
    "othernames": "Haushaltszucker",
    "enumber": "",
    "containedin": "diverse Lebensmittel",
    "category": "Zucker (raffiniert)",
    "cat-nr": 1,
    "sweetness": 1,
    "calories": 387,
    "gi": 65,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "bedingt",
    "notes": "Besteht je zur Hälfte aus Fruktose und Glukose. Regt bei regelmäßigem Konsum die Fettproduktion in der Leber an."
  },
  {
    "name": "Isoglukose",
    "symbol": "Ig",
    "othernames": "Fruktose-Glukose-Sirup",
    "enumber": "",
    "containedin": "Limonaden, Desserts, Süßigkeiten",
    "category": "Zucker (raffiniert)",
    "cat-nr": 1,
    "sweetness": 1.2,
    "calories": 387,
    "gi": 60,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Besteht wie Haushaltszucker aus Fruktose und Glukose, wobei der Anteil an Fruktose bis zu 90&nbsp;Prozent betragen kann."
  },
  {
    "name": "Invertzucker",
    "symbol": "In",
    "othernames": "Invertose, Invertzuckersirup",
    "enumber": "",
    "containedin": "Cocktails, Süßigkeiten, Müsliriegel",
    "category": "Zucker (raffiniert)",
    "cat-nr": 1,
    "sweetness": 1,
    "calories": 387,
    "gi": 60,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Ernährungsphysiologisch wie Saccharose. Wird wegen seiner flüssigen Konsistenz gerne zur Süßung von Cocktails und Bonbonfüllungen verwendet."
  },
  {
    "name": "Glukose",
    "symbol": "Gl",
    "othernames": "Traubenzucker",
    "enumber": "",
    "containedin": "Gebäck, Eis, Süßspeisen",
    "category": "Zucker (raffiniert)",
    "cat-nr": 1,
    "sweetness": 0.7,
    "calories": 374,
    "gi": 100,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Lässt den Blutzuckerspiegel schnell ansteigen."
  },
  {
    "name": "Tagatose",
    "symbol": "Tg",
    "othernames": "",
    "enumber": "",
    "containedin": "Diät-Trinkeis (USA), Überzugmittel Frühstücksflocken (USA)",
    "category": "Zucker (raffiniert)",
    "cat-nr": 1,
    "sweetness": 0.9,
    "calories": 150,
    "gi": 3,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Zählt zu den Ketohexosen. Fast so süß wie Haushaltszucker, lässt aber den Blutzuckerspiegel kaum ansteigen."
  },
  {
    "name": "Honig",
    "symbol": "Hn",
    "othernames": "",
    "enumber": "",
    "containedin": "Lebkuchen, Süßwaren, Riegel, Feinkost",
    "category": "Naturstoff (roh)",
    "cat-nr": 2,
    "sweetness": 0.97,
    "calories": 300,
    "gi": 60,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Besteht vor allem aus Fuktose und Glukose sowie Wasser. Wirkt entzündungshemmend, kann aber mit Pestiziden und Keimen belastet sein. Daher nicht für Säuglinge geeignet."
  },
  {
    "name": "Yacón-Sirup",
    "symbol": "Yc",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (roh)",
    "cat-nr": 2,
    "sweetness": 0.5,
    "calories": 280,
    "gi": 40,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Reich an Ballaststoffen, wirkt verdauungsfördernd."
  },
  {
    "name": "Lucuma-Pulver",
    "symbol": "Lu",
    "othernames": "",
    "enumber": "",
    "containedin": "Nahrungsergänzungsmittel",
    "category": "Naturstoff (roh)",
    "cat-nr": 2,
    "sweetness": 0.5,
    "calories": 350,
    "gi": 25,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "bedingt",
    "notes": "Nicht wasserlöslich. Mögliche Langzeitrisiken und die Wirkung auf den Stoffwechsel sind bislang wissenschaftlich kaum untersucht."
  },
  {
    "name": "Mönchsfrucht-Extrakt",
    "symbol": "Mf",
    "othernames": "Lu Han Guo",
    "enumber": "",
    "containedin": "(exotische) Getränke",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 300,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Auch als Heilmittel in der traditionellen chinesischen Medizin verwendet. Die Süßkraft stammt von so genannten Mogrosiden, die zur Stoffklasse der Triterpensaponine gehören."
  },
  {
    "name": "Zuckerrohrmelasse",
    "symbol": "Zm",
    "othernames": "",
    "enumber": "",
    "containedin": "Lakritz, Zerealien, BBQ-Soßen, Ketchup",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 0.8,
    "calories": 290,
    "gi": 60,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose": "nein",
    "notes": "Nebenprodukt beim Raffinieren von Haushaltszucker. Enthält Antioxidanzien, Minerale und B-Vitamine. Eigengeschmack leicht bitter."
  },
  {
    "name": "Thaumatin",
    "symbol": "Th",
    "othernames": "",
    "enumber": "E 957",
    "containedin": "Süßwaren, Diät-, Nahrungsergänzungsmittel, Kaugummis",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 2000,
    "calories": 400,
    "gi": 0,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Besteht aus Proteinen, die aus der westafrikanischen Katamfrucht isoliert werden. Man braucht nur sehr geringe Mengen, da es extrem süß ist."
  },
  // {
  //   "name": "brauner Zucker",
  //   "symbol": "Br",
  //   "othernames": "",
  //   "enumber": "",
  //   "containedin": "Backwaren, Desserts, Marinaden",
  //   "category": "Naturstoff (verarbeitet)",
  //   "cat-nr": 3,
  //   "sweetness": 1,
  //   "calories": 387,
  //   "gi": 64,
  //   "tooth": "nein",
  //   "heat": "ja",
  //   "laxative": "ja",
  //   "aftertaste": "ja",
  //   "fructose": "bedingt",
  //   "notes": "Nicht vollständig aufgereinigter oder nachträglich mit Melasse angefärbter Zucker."
  // },
  {
    "name": "Kokosblütenzucker",
    "symbol": "Kb",
    "othernames": "",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 1,
    "calories": 380,
    "gi": 50,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "bedingt",
    "notes": "Aus dem Nektar der Kokosnuss-Blüte. Ähnliche Zusammensetzung wie Haushaltszucker, löst sich in Rührteigen aber schlechter auf, was sich auf das Volumen des Gebäcks auswirken kann."
  },
  {
    "name": "Reissirup",
    "symbol": "Re",
    "othernames": "",
    "enumber": "",
    "containedin": "fruktosefreie Produkte",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 0.6,
    "calories": 320,
    "gi": 100,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Enthält vor allem Glukose und Maltose. Kann mit Arsen belastet sein."
  },
  {
    "name": "Agavendicksaft",
    "symbol": "Ag",
    "othernames": "Agavensirup",
    "enumber": "",
    "containedin": "Gebäck, Desserts, Süßigkeiten",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 1.3,
    "calories": 300,
    "gi": 15,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Enthält sehr viel Fruktose."
  },
  {
    "name": "Ahornsirup",
    "symbol": "As",
    "othernames": "",
    "enumber": "",
    "containedin": "Speiseeis, Müsli, Riegel",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 0.7,
    "calories": 260,
    "gi": 65,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Hauptsächlich aus Saccharose. Enthält Mineralien und Vitamine."
  },
  {
    "name": "Sorghumsirup",
    "symbol": "Sg",
    "othernames": "Zuckerhirse",
    "enumber": "",
    "containedin": "",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 1.1,
    "calories": 290,
    "gi": 60,
    "tooth": "nein",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Schmeckt leicht bitter und erdig."
  },
  {
    "name": "Glycyrrhizin",
    "symbol": "Gl",
    "othernames": "Süßholz, Lakritze",
    "enumber": "",
    "containedin": "Lakritze, Tabakprodukte",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 50,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Kann im Übermaß Bluthochdruck auslösen. Wird bei Infekten der oberen Luftwege eingesetzt."
  },
  {
    "name": "Steviaglycoside",
    "symbol": "St",
    "othernames": "Stevia",
    "enumber": "E 960",
    "containedin": "Getränke, Süßigkeiten, Fruchtaufstriche",
    "category": "Naturstoff (verarbeitet)",
    "cat-nr": 3,
    "sweetness": 300,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose": "ja",
    "notes": "Laut der Europäischen Behörde für Lebensmittelsicherheit (EFSA) sollte man täglich nicht mehr als 4&nbsp;Milligramm pro Kilogramm Körpergewicht aufnehmen. Kinder können den Wert schnell überschreiten."
  },
  {
    "name": "Polyglycitolsirup",
    "symbol": "Pg",
    "othernames": "hydrierter Glukosesirup",
    "enumber": "E 964",
    "containedin": "Speiseeis, Desserts",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.8,
    "calories": 240,
    "gi": 39,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Wegen seiner flüssigen Konsistenz gut geeignet für Speiseeis und andere Süßspeisen. Einziger Zuckeralkohol mit vorgeschriebener Höchstmenge."
  },
  {
    "name": "Maltit",
    "symbol": "Ml",
    "othernames": "Maltitol",
    "enumber": "E 965",
    "containedin": "Marmelade, Kaugummis, Backwaren",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.9,
    "calories": 200,
    "gi": 52,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Aus Maltose hergestellt. Hat einen leichten Karamellgeschmack."
  },
  {
    "name": "Lactit",
    "symbol": "Lt",
    "othernames": "Lactitol",
    "enumber": "E 966",
    "containedin": "Backwaren, Senf, Saucen",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.4,
    "calories": 200,
    "gi": 6,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Wird aus Milchzucker hergestellt."
  },
  {
    "name": "Xylit",
    "symbol": "Xy",
    "othernames": "Xylitol, Birkenzucker",
    "enumber": "E 967",
    "containedin": "Zahnpflege-Kaugummis, Zahncreme",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 1,
    "calories": 240,
    "gi": 10,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Gut für die Zähne. Einer Studie von 2024 zufolge sollen große Mengen Xylit das Risiko für schwere Herzerkrankungen und Schlaganfälle deutlich erhöhen."
  },
  {
    "name": "Sorbit",
    "symbol": "Sb",
    "othernames": "Sorbitol",
    "enumber": "E 420",
    "containedin": "Zahncreme, Kaugummis",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.6,
    "calories": 240,
    "gi": 7,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Blockiert den Fruktosetransporter GLUT-5 im Darm und provoziert damit Symptome einer Fruktoseunverträglichkeit. Auch als Feuchthaltemittel verwendet."
  },
  {
    "name": "Mannit",
    "symbol": "Mn",
    "othernames": "Mannitol",
    "enumber": "E 421",
    "containedin": "Süßwaren, Desserts, Kaugummis",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.7,
    "calories": 240,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Hartbeschichtung für Pillen. Wird als Abführmittel genutzt."
  },
  {
    "name": "Isomalt",
    "symbol": "Is",
    "othernames": "",
    "enumber": "E 953",
    "containedin": "Bonbons, Kaugummis, Desserts",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.5,
    "calories": 200,
    "gi": 7,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "nein",
    "notes": "Nimmt so gut wie keine Feuchtigkeit aus der Luft auf, verklumpt daher nicht."
  },
  {
    "name": "Erythrit",
    "symbol": "Er",
    "othernames": "Erythritol",
    "enumber": "E 968",
    "containedin": "Kaugummis, Bonbons",
    "category": "Zuckeralkohol",
    "cat-nr": 4,
    "sweetness": 0.5,
    "calories": 20,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "nein",
    "aftertaste": "ja",
    "fructose": "bedingt",
    "notes": "Im Vergleich zu den anderen Zuckeralkoholen besonders verträglich. Käse und Früchte wie Weintrauben, Birnen und Melonen enthalten natürliches Erythrit. Kann Risiko für Herz-Kreislauf-Erkrankungen erhöhen."
  },
  {
    "name": "Saccharin",
    "symbol": "Sc",
    "othernames": "",
    "enumber": "E 954",
    "containedin": "Limonaden, Süßstofftabletten, Diätprodukte",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 550,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose": "ja",
    "notes": "Ältester Süßstoff auf dem deutschen Markt. Wurde immer wieder auf kanzerogene Wirkung untersucht, ein Zusammenhang zu Krebserkrankungen konnte aber nie sicher nachgewiesen werden. Empfohlene Höchstmenge pro Tag: 5&nbsp;Milligramm pro Kilogramm Körpergewicht."
  },
  {
    "name": "Sucralose",
    "symbol": "Sr",
    "othernames": "Splenda (USA)",
    "enumber": "E 955",
    "containedin": "Limonaden, Energy Drinks",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 600,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Bleibt in der Umwelt stabil und beeinflusst dort die Mikroflora. Beim Erhitzen über 120 °C entstehen gesundheitsschädliche Stoffe. Empfohlene Höchstmenge pro Tag: 15&nbsp;Milligramm pro Kilogramm Körpergewicht."
  },
  {
    "name": "Aspartam",
    "symbol": "As",
    "othernames": "Nutrasweet (USA)",
    "enumber": "E 951",
    "containedin": "Getränke, Süßwaren, Desserts",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 200,
    "calories": 400,
    "gi": 0,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Von der Krebsforschungsagentur IARC 2023 als &raquo;möglicherweise krebserregend&laquo; eingestuft. Empfohlene Höchstmenge pro Tag: 40&nbsp;Milligramm pro Kilogramm Körpergewicht. Nicht geeignet für Menschen mit der Stoffwechselkrankheit Phenylketonurie. Der hohe Brennwert ist im Gebrauch zu vernachlässigen, da man nur winzige Mengen benötigt."
  },
  {
    "name": "Acesulfam-Aspartam-Salz",
    "symbol": "Aa",
    "othernames": "Twinsweet",
    "enumber": "E 962",
    "containedin": "Getränke, Süßwaren, Desserts",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 350,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Reaktionsprodukt aus Aspartam und Acesulfam. Nicht geignet für Menschen mit der Stoffwechselkrankheit Phenylketonurie."
  },
  {
    "name": "Advantam",
    "symbol": "Ad",
    "othernames": "",
    "enumber": "E 969",
    "containedin": "Süßwaren, Brotaufstrich, Soßen",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 20000,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "nein",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Aus Aspartam hergestellt. Verstärkt den Geschmack von Zitrus sowie Minze. Empfohlene Höchstmenge pro Tag: 5&nbsp;Milligramm pro Kilogramm Körpergewicht."
  },
  {
    "name": "Neotam",
    "symbol": "Ne",
    "othernames": "",
    "enumber": "E 961",
    "containedin": "Backwaren, Senf",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 8000,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Aus Aspartam hergestellt. Verstärkt den Geschmack von Früchten wie Zitrone sowie Vanille, Minze und Schokolade. Empfohlene Höchstmenge pro Tag: 2&nbsp;Milligramm pro Kilogramm Körpergewicht."
  },
  {
    "name": "Acesulfam-Kalium",
    "symbol": "Ac",
    "othernames": "Sunett",
    "enumber": "E 950",
    "containedin": "Getränke, Süßwaren, Zahnpasta",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 200,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "nein",
    "fructose": "ja",
    "notes": "In Kombination mit anderen Süßstoffen steigt die Süßkraft um ein Vielfaches. Sehr stabil, damit gut zu lagern und hitzebeständig. Empfohlene Höchstmenge pro Tag: 9&nbsp;Milligramm pro Kilogramm Körpergewicht."
  },
  {
    "name": "Cyclamat",
    "symbol": "Cy",
    "othernames": "",
    "enumber": "E 952",
    "containedin": "Limonaden, Süßstofftabletten, Diätprodukte",
    "category": "Synthetischer Süßstoff",
    "cat-nr": 5,
    "sweetness": 35,
    "calories": 0,
    "gi": 0,
    "tooth": "ja",
    "heat": "ja",
    "laxative": "ja",
    "aftertaste": "ja",
    "fructose": "ja",
    "notes": "Geringste Süßkraft unter den synthetischen Süßstoffen. Wird oft gemeinsam mit Saccharin eingesetzt, da die beiden ihre Süßkraft gegenseitig verstärken. Empfohlene Höchstmenge pro Tag: 7&nbsp;Milligramm pro Kilogramm Körpergewicht."
  }
]